development:
  adapter: mysql
  database: moore_demo_development
  encoding: utf8
  username: root
  password: root
  host: localhost

test:
  adapter: mysql
  database: moore_demo_test
  encoding: utf8
  username: root
  password: root
  host: localhost

